# Site settings
title: "2 OnZeRoad"
description: Carnet de voyages

currentLocation:
  coordinates: "46.43266788464754, 2.6338473366617725"
  name: "France"
  date: "01 mars 2024"

# set the encoding to utf-8
encoding: utf-8

# Files
baseurl:
pagesdir: pages
assets:
  libs: assets/libs
  owner: assets/owner
logo: logo.png
discus_shortname: 2onzeroad
email: 2onzeroad@gmail.com
url: ""
search: true
share: true
comments: true

# Read Time is a calculator tp provide post read-time based on word count. Usage is recommended.
readtime: true

# Specify the average Words per minute. If not defined, 180 will be used
wpm: 200

# Owner/author information
owner:
  name: 2onzeroad
  avatar: avatar.png
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description: An amazing journey

# Social networking links used in footer. Update and remove as you like.
twitter_username:
facebook_username: 2onzeroad
github_username: 2onzeroad
deviantart_username:
500px_username:
flickr_username: 2onzeroad
instagram_username:

# Internal nav
nav:
  writing: "root_url/writing/"
  gallery: "root_url/gallery/"
  about: "root_url/about/"

# Server
destination: ./_site
port: 4000

#dependencies
# Gems
plugins:
  - jekyll-paginate

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  extensions:
    - Hard_wrap
    - no_intra_emphasis
    - strikethrough
    - fenced_code_blocks
    - autolink
    - tables
    - with_toc_data
    - highlight
    - footnotes
  input: GFM
sass:
  style: :compressed
paginate: 20
paginate_path: "/writing/page:num/"
permalink: "/writing/:title/"
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md"]
slugify: "pretty"

# Analytics and webmaster tools stuff goes here
google_analytics: UA-85699607-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
